version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
      - postgres

  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - .:/app/
    depends_on:
      - postgres
    command: [ "sh", "-c", "sleep 10 && php /app/initialize_db.php && php-fpm" ]


  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: savespace
    volumes:
        - ./Docker/postgres/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@savespace.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    depends_on:
      - postgres

volumes:
  pg_data: